### ISSUE TITLE
Cannot create workplace

### ISSUE THREAD

**Issue by istvank** [rwth-acis/ARLEMPanel#4]
On the "Create Workplace" page, after entering a name and clicking "SAVE WORKPLACE", there is a toast coming with:
"name" must be a string.

Also, the browser console is saying:
app.js:13700 POST http://127.0.0.1:8080/api/workplace 401 (Unauthorized)

**Comment by istvank** [comment]
@rizalishan could it be, that I first have to click "Start Adding Items", then navigate back, and then click "Create Workplace"? Is this a feature or a bug?

**Comment by rizalishan** [comment]
I guess once you added the name you directly clicked the tabs on the left side. If so, then it goes like this ... in the first step you add the name and then press "Start adding items" that would save the workplace name and then you can add items.
